detection:
  path: "./models/craft.onnx"
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

recognition:
  path: "./models/parseq.onnx"
  mean: 0.5
  std: 0.5

postprocess:
  text_threshold: 0.7
  link_threshold: 0.4
  low_text: 0.4
  area_threshold: 30
  patch_size: [32, 128]  # [height, width]

decoder:
  charset: "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~"